import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest) {
    // const searchParams = req.nextUrl.searchParams
    // const keyword = searchParams.get('keyword')
    // if (!keyword) {
    //     return NextResponse.json({ results: [] }, {
    //         status: 400
    //     });
    // }
    // const results = DUMMY_DATA.filter((data) => data.name.includes(keyword));
    const results = DUMMY_DATA;

    return NextResponse.json(results, { status: 200 });
}


const DUMMY_DATA = [
    {
        id: 0,
        logo: "/assets/logo/1.png",
        joinDate: "2023-07-31",
        name: "검색어1",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 1,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어2",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 2,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어3",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 3,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어4",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 4,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어5",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 5,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어6",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 6,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어7",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",
    }, {
        id: 0,
        logo: "/assets/logo/1.png",
        joinDate: "2023-07-31",
        name: "검색어1",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 1,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어2",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 2,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어3",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 3,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어4",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 4,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어5",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 5,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어6",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 6,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어7",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",
    }, {
        id: 0,
        logo: "/assets/logo/1.png",
        joinDate: "2023-07-31",
        name: "검색어1",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 1,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어2",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 2,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어3",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 3,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어4",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 4,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어5",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 5,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어6",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 6,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어7",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",
    }, {
        id: 0,
        logo: "/assets/logo/1.png",
        joinDate: "2023-07-31",
        name: "검색어1",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 1,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어2",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 2,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어3",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 3,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어4",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 4,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어5",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 5,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어6",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 6,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어7",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",
    }, {
        id: 0,
        logo: "/assets/logo/1.png",
        joinDate: "2023-07-31",
        name: "검색어1",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 1,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어2",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 2,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어3",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 3,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어4",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 4,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어5",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 5,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어6",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 6,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어7",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",
    }, {
        id: 0,
        logo: "/assets/logo/1.png",
        joinDate: "2023-07-31",
        name: "검색어1",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 1,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어2",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 2,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어3",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 3,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어4",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 4,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어5",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 5,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어6",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 6,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어7",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",
    }, {
        id: 0,
        logo: "/assets/logo/1.png",
        joinDate: "2023-07-31",
        name: "검색어1",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 1,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어2",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 2,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어3",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 3,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어4",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 4,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어5",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 5,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어6",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 6,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어7",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",
    }, {
        id: 0,
        logo: "/assets/logo/1.png",
        joinDate: "2023-07-31",
        name: "검색어1",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 1,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어2",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 2,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어3",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 3,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어4",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 4,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어5",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 5,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어6",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",

    },
    {
        id: 6,
        logo: "/assets/logo/0.png",
        joinDate: "2024-07-31",
        name: "검색어7",
        rating: 4.5,
        reviewCount: 1000,
        category: "대표소분류",
        location: "서울시 강남구",
        reward: "gift",
        description: "최대 글자 수는 공백 포함 21자까지 작성 가능합니다",
    },

];